2020-11-19 09:27:19,401 (70314/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-11-19 09:27:19,401 (70314/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-11-19 09:27:19,409 (70314/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0_1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 562, in connect\n    raise e\n  File "/usr/local/Cellar/pgcli/3.0.0_1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 549, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.0.0_1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.0.0_1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/Cellar/pgcli/3.0.0_1/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/usr/local/Cellar/pgcli/3.0.0_1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: FATAL:  database "cassio.marques" does not exist\n\n'
2020-11-19 09:27:25,145 (70323/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-11-19 09:27:25,145 (70323/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-11-19 09:27:33,245 (70332/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-11-19 09:27:33,246 (70332/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-11-19 09:28:14,100 (70332/MainThread) pgcli.main ERROR - sql: 'select * from applicants;', error: StopIteration()
2020-11-19 09:28:14,100 (70332/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0_1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 634, in execute_command\n    output, query = self._evaluate_command(text)\n  File "/usr/local/Cellar/pgcli/3.0.0_1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 909, in _evaluate_command\n    formatted = format_output(title, cur, headers, status, settings)\n  File "/usr/local/Cellar/pgcli/3.0.0_1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 1432, in format_output\n    first_line = next(formatted)\nStopIteration\n'
